// Copyright (c) 2024-present The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit/.

/**
 * Tool to convert a compact-serialized UTXO set to a SQLite3 database.
 *
 * The input UTXO set can be generated by Bitcoin Core with the `dumptxoutset` RPC:
 * $ bitcoin-cli dumptxoutset ~/utxos.dat latest
 *
 * The created database contains a table `utxos` with the following schema:
 * (txid TEXT, vout INT, value INT, coinbase INT, height INT, scriptpubkey TEXT)
 *
 * If --txid=raw or --txid=rawle is specified, txid will be BLOB instead;
 * if --spk=raw, then scriptpubkey will be BLOB instead.
 */

#include <compressor.h>
#include <crypto/hex_base.h>
#include <node/utxo_snapshot.h>
#include <pubkey.h>
#include <script/script.h>
#include <serialize.h>
#include <streams.h>
#include <tinyformat.h>
#include <uint256.h>
#include <util/string.h>

#include <sqlite3.h>

#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <iostream>
#include <cstdlib>
#include <cstring>
#include <optional>
#include <string>
#include <utility>
#include <vector>

//! Magic constant for write batching - each batch commits to SQLite
static constexpr uint64_t WRITE_BATCH_SIZE = 16 * 1024;

//! Progress is printed every N coins
static constexpr uint64_t PROGRESS_INTERVAL = 1024 * 1024;

//! Network magic to human-readable name mapping
static const std::vector<std::pair<std::array<uint8_t, 4>, std::string>> NETWORK_MAGIC_NAMES = {
    {{{0xf9, 0xbe, 0xb4, 0xd9}}, "Mainnet"},
    {{{0x0a, 0x03, 0xcf, 0x40}}, "Signet"},
    {{{0x0b, 0x11, 0x09, 0x07}}, "Testnet3"},
    {{{0x1c, 0x16, 0x3f, 0x28}}, "Testnet4"},
    {{{0xfa, 0xbf, 0xb5, 0xda}}, "Regtest"},
};

/**
 * Convert a 4-byte network magic to its human-readable name.
 * @param network_magic The 4-byte network magic bytes
 * @return The network name, or a hex dump string if unknown
 */
static std::string GetNetworkName(std::array<uint8_t, 4> network_magic)
{
    for (const auto& [magic, name] : NETWORK_MAGIC_NAMES) {
        if (magic == network_magic) {
            return name;
        }
    }
    return strprintf("unknown network (%s)", HexStr(network_magic));
}

/**
 * Decompress a script from the compact format used in UTXO snapshots.
 *
 * Uses ScriptCompression from the compressor module, which handles all
 * special cases (P2PKH, P2SH, compressed/uncompressed P2PK) and regular scripts.
 *
 * @param file Buffered file stream to read compressed script from
 * @return Decompressed script bytes
 */
static std::vector<uint8_t> DecompressScript(BufferedFile& file)
{
    unsigned int nSize;
    file >> VARINT(nSize);

    CScript script;

    if (nSize < ScriptCompression::nSpecialScripts) {
        // Special cases (0-5): P2PKH, P2SH, compressed P2PK, uncompressed P2PK
        const unsigned int len = GetSpecialScriptSize(nSize);
        CompressedScript compressed(len, 0x00);
        file.read(std::as_writable_bytes(std::span{compressed}));
        DecompressScript(script, nSize, compressed);
    } else {
        // Regular scripts
        nSize -= ScriptCompression::nSpecialScripts;
        if (nSize > MAX_SCRIPT_SIZE) {
            throw std::runtime_error(strprintf("Too long script with size %u", nSize));
        }
        script.resize(nSize);
        file.read(std::as_writable_bytes(std::span{script}));
    }

    return std::vector<uint8_t>(script.begin(), script.end());
}

//! Output format for transaction IDs
enum class TxidFormat {
    Hex,    //!< Hex string (reversed for display)
    Raw,    //!< Raw bytes in internal (sha256) byte order
    RawLE,  //!< Raw bytes in little-endian (reversed) byte order
};

//! Output format for scriptPubKey
enum class SpkFormat {
    Hex,  //!< Hex string
    Raw,  //!< Raw bytes
};

//! Per-UTXO data for SQLite insertion
struct CoinRecord {
    uint256 txid;
    uint32_t vout;
    uint64_t value;
    bool coinbase;
    uint32_t height;
    std::vector<uint8_t> scriptPubKey;
};

/**
 * Print usage information to stdout.
 */
static void PrintHelp()
{
    tfm::format(std::cout, R"(Usage: bitcoin-utxo-to-sqlite [options] <inputfile> <outputfile>

Convert a compact-serialized UTXO set to a SQLite3 database.

The input UTXO set can be generated by Bitcoin Core with the `dumptxoutset` RPC:
  $ bitcoin-cli dumptxoutset ~/utxos.dat latest

The created database contains a table `utxos` with the following schema:
  (txid TEXT, vout INT, value INT, coinbase INT, height INT, scriptpubkey TEXT)

If --txid=raw or --txid=rawle is specified, txid will be BLOB instead;
if --spk=raw, then scriptpubkey will be BLOB instead.

Options:
  --verbose          Show details about each UTXO
  --spk=FORMAT       Encode scriptPubKey as hex or raw bytes (default: hex)
                     FORMAT is 'hex' or 'raw'
  --txid=FORMAT      Encode txid as hex, raw bytes (sha256 byteorder),
                     or reversed raw bytes (little endian) (default: hex)
                     FORMAT is 'hex', 'raw', or 'rawle'
  -h, --help         Show this help message
)");
}

int main(int argc, char* argv[])
{
    // Parse command-line arguments manually for portability
    std::string input_file;
    std::string output_file;
    bool verbose = false;
    TxidFormat txid_format = TxidFormat::Hex;
    SpkFormat spk_format = SpkFormat::Hex;

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-h" || arg == "--help") {
            PrintHelp();
            return EXIT_SUCCESS;
        } else if (arg == "--verbose") {
            verbose = true;
        } else if (arg.starts_with("--spk=")) {
            std::string format = arg.substr(6);
            if (format == "hex") {
                spk_format = SpkFormat::Hex;
            } else if (format == "raw") {
                spk_format = SpkFormat::Raw;
            } else {
                tfm::format(std::cerr, "Error: invalid --spk value '%s' (use 'hex' or 'raw')\n", format);
                return EXIT_FAILURE;
            }
        } else if (arg.starts_with("--txid=")) {
            std::string format = arg.substr(7);
            if (format == "hex") {
                txid_format = TxidFormat::Hex;
            } else if (format == "raw") {
                txid_format = TxidFormat::Raw;
            } else if (format == "rawle") {
                txid_format = TxidFormat::RawLE;
            } else {
                tfm::format(std::cerr, "Error: invalid --txid value '%s' (use 'hex', 'raw', or 'rawle')\n", format);
                return EXIT_FAILURE;
            }
        } else if (input_file.empty()) {
            input_file = arg;
        } else if (output_file.empty()) {
            output_file = arg;
        } else {
            tfm::format(std::cerr, "Error: unexpected argument '%s'\n", arg);
            PrintHelp();
            return EXIT_FAILURE;
        }
    }

    // Validate required arguments
    if (input_file.empty() || output_file.empty()) {
        tfm::format(std::cerr, "Error: missing required arguments\n");
        PrintHelp();
        return EXIT_FAILURE;
    }

    // Open input file for binary reading
    FILE* input = std::fopen(input_file.c_str(), "rb");
    if (!input) {
        tfm::format(std::cerr, "Error: input file '%s' does not exist or cannot be opened\n", input_file);
        return EXIT_FAILURE;
    }

    // Verify output file doesn't already exist
    FILE* test_output = std::fopen(output_file.c_str(), "rb");
    if (test_output) {
        std::fclose(test_output);
        tfm::format(std::cerr, "Error: output file '%s' already exists\n", output_file);
        std::fclose(input);
        return EXIT_FAILURE;
    }

    // Set up buffered file reader with 1MB buffer and 512KB rewind capacity
    AutoFile file{input};
    BufferedFile bf{file, 1 << 20, 512 << 10};

    // Read and validate magic bytes (5 bytes: "utxo" + 0xff)
    std::array<uint8_t, 5> magic;
    bf.read(std::as_writable_bytes(std::span{magic}));
    if (magic != SNAPSHOT_MAGIC_BYTES) {
        tfm::format(std::cerr, "Error: provided input file '%s' is not a UTXO dump (bad magic bytes)\n", input_file);
        return EXIT_FAILURE;
    }

    // Read version (must be 2)
    uint16_t version;
    bf >> version;
    if (version != 2) {
        tfm::format(std::cerr, "Error: provided input file '%s' has unknown UTXO dump version %u (only version 2 supported)\n",
                    input_file, version);
        return EXIT_FAILURE;
    }

    // Read and map network magic to network name
    std::array<uint8_t, 4> network_magic;
    bf.read(std::as_writable_bytes(std::span{network_magic}));
    const std::string network_name = GetNetworkName(network_magic);

    // Read block hash (32 bytes, internally stored as-is)
    uint256 block_hash;
    bf >> block_hash;

    // Read total number of UTXOs in the snapshot (raw uint64_t, not VARINT)
    uint64_t num_utxos = ser_readdata64(bf);

    tfm::format(std::cout, "UTXO Snapshot for %s at block hash %s..., contains %s coins\n",
                network_name,
                block_hash.GetHex().substr(0, 32),
                static_cast<unsigned long long>(num_utxos));

    const auto start_time = std::chrono::steady_clock::now();

    // Open SQLite database for writing
    sqlite3* db = nullptr;
    int rc = sqlite3_open(output_file.c_str(), &db);
    if (rc != SQLITE_OK) {
        tfm::format(std::cerr, "Error: cannot open database '%s': %s\n", output_file, sqlite3_errmsg(db));
        return EXIT_FAILURE;
    }

    // Determine SQLite column types based on format options
    const std::string txid_type = (txid_format == TxidFormat::Hex) ? "TEXT" : "BLOB";
    const std::string spk_type = (spk_format == SpkFormat::Hex) ? "TEXT" : "BLOB";

    // Create the utxos table
    const std::string create_sql = strprintf("CREATE TABLE utxos(txid %s, vout INT, value INT, coinbase INT, height INT, scriptpubkey %s)",
                                            txid_type, spk_type);
    rc = sqlite3_exec(db, create_sql.c_str(), nullptr, nullptr, nullptr);
    if (rc != SQLITE_OK) {
        tfm::format(std::cerr, "Error: cannot create table: %s\n", sqlite3_errmsg(db));
        sqlite3_close(db);
        return EXIT_FAILURE;
    }

    // Prepare parameterized insert statement for efficiency
    sqlite3_stmt* stmt = nullptr;
    rc = sqlite3_prepare_v2(db, "INSERT INTO utxos VALUES(?, ?, ?, ?, ?, ?)", -1, &stmt, nullptr);
    if (rc != SQLITE_OK) {
        tfm::format(std::cerr, "Error: cannot prepare statement: %s\n", sqlite3_errmsg(db));
        sqlite3_close(db);
        return EXIT_FAILURE;
    }

    // Begin transaction for faster inserts
    sqlite3_exec(db, "BEGIN TRANSACTION", nullptr, nullptr, nullptr);

    // Track state for grouped UTXO reads
    uint64_t coins_per_hash_left = 0;
    uint256 prevout_hash;
    uint32_t max_height = 0;

    // Process each UTXO
    for (uint64_t coin_idx = 1; coin_idx <= num_utxos; ++coin_idx) {
        // Read key (COutPoint) - txid and output index
        if (coins_per_hash_left == 0) {
            bf >> prevout_hash;
            bf >> COMPACTSIZE(coins_per_hash_left);
        }
        uint64_t prevout_index;
        bf >> COMPACTSIZE(prevout_index);

        // Read value (Coin) - amount, script, and metadata
        uint64_t code;
        bf >> VARINT(code);
        const uint32_t height = code >> 1;
        const bool is_coinbase = (code & 1) != 0;

        uint64_t compressed_amount;
        bf >> VARINT(compressed_amount);
        const uint64_t amount = DecompressAmount(compressed_amount);

        const std::vector<uint8_t> scriptpubkey = DecompressScript(bf);

        if (height > max_height) {
            max_height = height;
        }

        // Format txid according to user preference
        std::string txid_value;
        if (txid_format == TxidFormat::Hex) {
            // For hex mode, reverse the internal byte order to match Python's behavior
            // Python does: prevout_hash[::-1].hex() which reverses before hex encoding
            // uint256.GetHex() shows internal order with first byte at end
            std::array<uint8_t, 32> reversed_data;
            std::reverse_copy(prevout_hash.begin(), prevout_hash.end(), reversed_data.begin());
            txid_value = HexStr(reversed_data);
        }
        // For Raw format, we use the bytes directly below

        // Format scriptpubkey according to user preference
        std::string spk_value;
        if (spk_format == SpkFormat::Hex) {
            spk_value = HexStr(scriptpubkey);
        }
        // For Raw format, we use the bytes directly below

        if (verbose) {
            tfm::format(std::cout, "Coin %s/%s:\n", static_cast<unsigned long long>(coin_idx), static_cast<unsigned long long>(num_utxos));
            tfm::format(std::cout, "    prevout = %s:%s\n", prevout_hash.GetHex(), static_cast<unsigned long long>(prevout_index));
            tfm::format(std::cout, "    amount = %s, height = %s, coinbase = %s\n", static_cast<unsigned long long>(amount), height, is_coinbase);
            tfm::format(std::cout, "    scriptPubKey = %s\n\n", HexStr(scriptpubkey));
        }

        // Bind parameters to the insert statement
        int param_idx = 1;

        if (txid_format == TxidFormat::Hex) {
            sqlite3_bind_text(stmt, param_idx++, txid_value.c_str(), -1, SQLITE_STATIC);
        } else {
            // Raw/RawLE: store as BLOB
            // Raw: internal byte order; RawLE: reversed byte order
            std::vector<uint8_t> txid_bytes(prevout_hash.begin(), prevout_hash.end());
            if (txid_format == TxidFormat::RawLE) {
                std::reverse(txid_bytes.begin(), txid_bytes.end());
            }
            sqlite3_bind_blob(stmt, param_idx++, txid_bytes.data(), txid_bytes.size(), SQLITE_TRANSIENT);
        }

        sqlite3_bind_int64(stmt, param_idx++, prevout_index);
        sqlite3_bind_int64(stmt, param_idx++, amount);
        sqlite3_bind_int(stmt, param_idx++, is_coinbase ? 1 : 0);
        sqlite3_bind_int(stmt, param_idx++, height);

        if (spk_format == SpkFormat::Hex) {
            sqlite3_bind_text(stmt, param_idx++, spk_value.c_str(), -1, SQLITE_STATIC);
        } else {
            sqlite3_bind_blob(stmt, param_idx++, scriptpubkey.data(), scriptpubkey.size(), SQLITE_STATIC);
        }

        // Execute the insert
        rc = sqlite3_step(stmt);
        if (rc != SQLITE_DONE) {
            tfm::format(std::cerr, "Error: cannot insert row: %s\n", sqlite3_errmsg(db));
            sqlite3_finalize(stmt);
            sqlite3_close(db);
            return EXIT_FAILURE;
        }
        sqlite3_reset(stmt);  // Clear bindings for next iteration

        coins_per_hash_left--;

        // Print progress at intervals
        if (coin_idx % PROGRESS_INTERVAL == 0) {
            const auto elapsed = std::chrono::steady_clock::now() - start_time;
            const double elapsed_secs = std::chrono::duration<double>(elapsed).count();
            tfm::format(std::cout, "%s coins converted [%.2f%%], %.3fs passed since start\n",
                        static_cast<unsigned long long>(coin_idx),
                        static_cast<double>(coin_idx) * 100.0 / static_cast<double>(num_utxos),
                        elapsed_secs);
        }

        // Batch commit every WRITE_BATCH_SIZE records
        if (coin_idx % WRITE_BATCH_SIZE == 0) {
            sqlite3_exec(db, "COMMIT", nullptr, nullptr, nullptr);
            sqlite3_exec(db, "BEGIN TRANSACTION", nullptr, nullptr, nullptr);
        }
    }

    // Finalize the last transaction
    sqlite3_exec(db, "COMMIT", nullptr, nullptr, nullptr);
    sqlite3_finalize(stmt);

    // Verify we've consumed the entire input file
    if (!bf.eof()) {
        tfm::format(std::cerr, "WARNING: input file '%s' has not reached EOF yet!\n", input_file);
    }

    sqlite3_close(db);

    tfm::format(std::cout, "TOTAL: %s coins written to %s, snapshot height is %s.\n",
                static_cast<unsigned long long>(num_utxos),
                output_file,
                max_height);

    return EXIT_SUCCESS;
}
